// AUTO-GENERATED by scripts/build-fcebuilder-presets.js from datamine/fce/data/bosses/*.json.
// Do not edit by hand; edit the per-boss files and rerun the script.
window.FCE_PRESETS = {
  "en": [
    {
      "slug": "chaos-armor",
      "name": "Chaos Armor",
      "boss_id": "boss_hum_046",
      "source_psd": "хаос.psd",
      "art": "./assets/bosses/chaos-armor.png",
      "art_object_position": "center center",
      "name_color": "#f16937",
      "mechanics": [
        {
          "index": "1",
          "html": "Attacks come with a powerful Graying Bite effect. Increase corresponding elemental resistance or avoid being hit."
        },
        {
          "index": "2",
          "html": "The lower the boss&#x27;s HP, the greater its damage reduction. <span class=\"fce-card__text-accent\">Damage reduction 20% for each 20% HP lost.</span> The boss can then be executed. Use weapons with high shatter to break its shield and execute it. Execution damage ignores the boss&#x27;s damage reduction and is affected by the Wanderer&#x27;s ATK, resistance, and damage boost."
        },
        {
          "index": "3",
          "html": "Gain the Infernal Flames skill. The majority of the boss&#x27;s attacks will leave a large area on the ground that burns continuously. Avoid entering the burning areas."
        },
        {
          "index": "4",
          "html": "Large random explosions will occur in the area, dealing lethal damage upon hit and leaving Infernal Flames in the area."
        }
      ]
    },
    {
      "slug": "frigg",
      "name": "Frigg",
      "boss_id": "boss_hum_019",
      "source_psd": "фригг.psd",
      "art": "./assets/bosses/frigg.png",
      "art_object_position": "center center",
      "name_color": "#ef62bd",
      "mechanics": [
        {
          "index": "1",
          "html": "Frigg's shield strength greatly increases."
        },
        {
          "index": "2",
          "html": "Frigg gains a damage boost each time she lands a hit. This effect can stack."
        },
        {
          "index": "3",
          "html": "Frigg enters Rampage Mode, greatly increasing her speed."
        },
        {
          "index": "4",
          "html": "Frigg enters Extreme Mode, increasing her speed and leaving frost under her feet. If you touch the frost, you will take damage and be slowed, which can be stacked up to 3 times."
        }
      ]
    },
    {
      "slug": "valkyrie",
      "name": "Valkyrie",
      "boss_id": "boss_hum_032",
      "source_psd": "валька.psd",
      "art": "./assets/bosses/valkyrie.png",
      "art_object_position": "center center",
      "name_color": "#ebe154",
      "mechanics": [
        {
          "index": "1",
          "html": "Valkyrie leaves destructible electrodes on the ground at regular intervals. These electrodes are periodically."
        },
        {
          "index": "2",
          "html": "Valkyrie is immune to damage 1 time every second."
        },
        {
          "index": "3",
          "html": "Valkyrie leaves destructible electrodes on the ground around it at regular intervals. These electrodes periodically emit a circular electrical current in the surrounding area."
        },
        {
          "index": "4",
          "html": "Valkyrie summons lightning bolts around it at regular intervals, dealing lethal damage and electrifying targets. When an electrified target is hit by a volt attack, chain lightning is triggered."
        }
      ]
    },
    {
      "slug": "culton",
      "name": "Culton",
      "boss_id": "boss_hum_036",
      "source_psd": "бегемот.psd",
      "art": "./assets/bosses/culton.png",
      "art_object_position": "center center",
      "name_color": "#4ec7d6",
      "mechanics": [
        {
          "index": "1",
          "html": "Culton triggers Hostility on the selected target every second. Each stack of Hostility slows the target for 5 seconds, stacking up to 5 times."
        },
        {
          "index": "2",
          "html": "Every 30 seconds, Culton induces chaos, reversing Wanderers&#x27; movement for 15 seconds."
        },
        {
          "index": "3",
          "html": "Culton becomes invincible for 3 seconds every time after losing 10% Max HP."
        },
        {
          "index": "4",
          "html": "In the final phase, Culton summons red pillars. Each pillar increases Culton&#x27;s damage boost and damage reduction by 20%. Make Culton collide with the pillars to disable the buffs."
        }
      ]
    },
    {
      "slug": "iron-tomb",
      "name": "Iron Tomb",
      "boss_id": "boss_hum_037",
      "source_psd": "саркафаг.psd",
      "art": "./assets/bosses/iron-tomb.png",
      "art_object_position": "center center",
      "name_color": "#3db0c0",
      "mechanics": [
        {
          "index": "1",
          "html": "Iron Tomb&#x27;s attacks have a certain chance to inflict a 5-second Countermove effect, disabling the target&#x27;s hyperbody for its duration."
        },
        {
          "index": "2",
          "html": "Every 20 seconds, Iron Tomb gains damage reduction based on its Max HP lost for 20 seconds. <span class=\"fce-card__text-accent\">Every 20 seconds calculate DMG reduction based on TOTAL HP lost. First 20% of HP lost: each 1% HP = 0.25% DMG reduction. Then each 1% HP lost = 0.5% DMG reduction.</span>"
        },
        {
          "index": "3",
          "html": "Every 8 seconds, Iron Tomb&#x27;s attacks inflict a Maim effect, significantly reducing the damage dealt and healing received on non-Fortitude targets for 8 seconds. <span class=\"fce-card__text-accent\">-50% Damage Dealt</span>"
        },
        {
          "index": "4",
          "html": "Every 20 seconds, Iron Tomb randomly links 2 players within range, reducing their final damage by 30%; each linked player provides a 30% increase in Iron Tomb&#x27;s final damage. Moving away from Iron Tomb can break the link."
        }
      ]
    },
    {
      "slug": "gaia",
      "name": "Gaia",
      "boss_id": "boss_hum_042",
      "source_psd": "гейр.psd",
      "art": "./assets/bosses/gaia.png",
      "art_object_position": "center center",
      "name_color": "#dc6dd0",
      "mechanics": [
        {
          "index": "1",
          "html": "Gaia inflicts Bonecrush on targets without Fortitude with each hit. At 20 stacks, the debuff triggers Cripple, massively reducing their damage dealt for 10 seconds."
        },
        {
          "index": "2",
          "html": "Every 15 seconds, Gaia randomly selects a target. After 5 seconds, the selected target inflicts wide-area lethal damage every second to all allies except themselves for 5 seconds."
        },
        {
          "index": "3",
          "html": "Targets hit by Gaia are slowed for 5 seconds, stacking up to 2 times."
        },
        {
          "index": "4",
          "html": "After Gaia&#x27;s shield is shattered, it deals wide-area damage every second for 10 seconds. Targets hit will be inflicted with 15% vulnerability for 10 seconds, stacking up to 3 times."
        }
      ]
    },
    {
      "slug": "sweetie",
      "name": "Sweetie",
      "boss_id": "boss_hum_020",
      "source_psd": "милашка.psd",
      "art": "./assets/bosses/sweetie.png",
      "art_object_position": "center center",
      "name_color": "#e08c42",
      "mechanics": [
        {
          "index": "1",
          "html": "Every 25 seconds, Sweetie imposes a penalty on 2–4 random nearby targets. If they perform any action within 5 seconds of the penalty being applied, they take damage."
        },
        {
          "index": "2",
          "html": "Increase Sweetie&#x27;s movement speed, and decrease the movement speed of all nearby targets."
        },
        {
          "index": "3",
          "html": "Every 15 seconds, Sweetie randomly selects a target on the field to inflict massive damage every second for 15 seconds, prioritizing targets with Fortitude Resonance."
        },
        {
          "index": "4",
          "html": "Sweetie chains all Wanderer-allied targets on the field. Each target will suffer damage proportional to the percentage of damage received by other chained targets. <span class=\"fce-card__text-accent\">Shares 10% DMG to every player. This DMG ignores Resists and DMG Reduction (except Asuka).</span>"
        }
      ]
    },
    {
      "slug": "merbelle",
      "name": "Merbelle",
      "boss_id": "boss_065",
      "source_psd": "мербель.psd",
      "art": "./assets/bosses/merbelle.png",
      "art_object_position": "center center",
      "name_color": "#a46ae7",
      "mechanics": [
        {
          "index": "1",
          "html": "Whenever Merbelle loses a certain amount of HP, its attack will increase."
        },
        {
          "index": "2",
          "html": "When Merbelle has a shield, gain additional damage reduction and greatly increase shield strength. <span class=\"fce-card__text-accent\">Additional 60% DMG reduction.</span>"
        },
        {
          "index": "3",
          "html": "Each time Merbelle deals damage, inflicts a stack of Flashfreeze. When Flashfreeze stacks 15 times, stacks clear and the Wanderer is greatly slowed for 6 seconds."
        },
        {
          "index": "4",
          "html": "Merbelle unleashes an ice pillar at a target every 15 seconds, dealing huge damage. The ice pillar remains on the field, restoring 3% of Merbelle&#x27;s Max HP every 10 seconds. The ice pillar can be destroyed by multiple attacks."
        }
      ]
    },
    {
      "slug": "frost-bot",
      "name": "Frost Bot",
      "boss_id": "boss_017",
      "source_psd": "морозныйбот.psd",
      "art": "./assets/bosses/frost-bot.png",
      "art_object_position": "center center",
      "name_color": "#4b8fff",
      "mechanics": [
        {
          "index": "1",
          "html": "Frost Bot continuously generates positioning generators around it. Each generator provides damage reduction to Frost Bot and can be shattered through multiple attacks. <span class=\"fce-card__text-accent\"> Damage reduction 20% for each ball with 90% limit.</span>"
        },
        {
          "index": "2",
          "html": "Frost Bot will repair itself, slowly recovering HP. <span class=\"fce-card__text-accent\">Recovers 0.5% of Max HP every 2 seconds.</span>"
        },
        {
          "index": "3",
          "html": "Greatly increase the movement speed of Frost Bot."
        },
        {
          "index": "4",
          "html": "Frost Bot releases a powerful chill around itself every second, continuously Slowing nearby targets."
        }
      ]
    },
    {
      "slug": "apophis",
      "name": "Apophis",
      "boss_id": "boss_014",
      "source_psd": "АПОФИС.psd",
      "art": "./assets/bosses/apophis.png",
      "art_object_position": "center center",
      "name_color": "#d4ba3e",
      "mechanics": [
        {
          "index": "1",
          "html": "Attacks come with a powerful Graying Bite effect. Increase corresponding elemental resistance or avoid being hit."
        },
        {
          "index": "2",
          "html": "Apophis can be destroyed. Use a high-shatter weapon to break his shield and destroy it."
        },
        {
          "index": "3",
          "html": "Greatly increase the movement speed of Apophis."
        },
        {
          "index": "4",
          "html": "Nullify the hyperbody status of targets around Apophis."
        }
      ]
    },
    {
      "slug": "minotaur",
      "name": "Minotaur",
      "boss_id": "boss_002",
      "source_psd": "МИНОТАВР.psd",
      "art": "./assets/bosses/minotaur.png",
      "art_object_position": "center center",
      "name_color": "#5d79dd",
      "mechanics": [
        {
          "index": "1",
          "html": "Minotaur significantly reduces damage received from the primary aggro target. <span class=\"fce-card__text-accent\">Damage reduction 80% from aggro.</span>"
        },
        {
          "index": "2",
          "html": "Minotaur can be executed. Use weapons with high shatter to break its shield and execute it."
        },
        {
          "index": "3",
          "html": "Every 15 seconds, Minotaur randomly selects a target with Benediction, applying Toxicitea, which converts the target&#x27;s healing into an equivalent amount of damage. Lasts for 10 seconds."
        },
        {
          "index": "4",
          "html": "Every 15 seconds, Minotaur examines all Wanderers. If a Wanderer is found to be within 5 meters without any other Wanderers nearby, that Wanderer will lose their hyperbody and invincibility and will be unable to regain hyperbody or invincibility for 90 seconds."
        }
      ]
    },
    {
      "slug": "rudolph",
      "name": "Rudolph",
      "boss_id": "boss_030",
      "source_psd": "РУДОЛЬФ.psd",
      "art": "./assets/bosses/rudolph.png",
      "art_object_position": "center center",
      "name_color": "#9adf3e",
      "mechanics": [
        {
          "index": "1",
          "html": "Greatly increase Rudolph&#x27;s Shield."
        },
        {
          "index": "2",
          "html": "Rudolph receives a massive damage reduction from the front, but its damage taken from behind is increased. <span class=\"fce-card__text-accent\"> Damage reduction 60% from front.</span>"
        },
        {
          "index": "3",
          "html": "Rudolph activates a wide-area Phantasia for 5 seconds at set intervals."
        },
        {
          "index": "4",
          "html": "Rudolph enters Rampage Mode, greatly increasing its movement speed."
        }
      ]
    },
    {
      "slug": "seraph",
      "name": "Seraph",
      "boss_id": "boss_010",
      "source_psd": "СЕРАФИМ.psd",
      "art": "./assets/bosses/seraph.png",
      "art_object_position": "center center",
      "name_color": "#ea6d49",
      "mechanics": [
        {
          "index": "1",
          "html": "Seraph's attacks carry an additional Powerful Graying Bite effect."
        },
        {
          "index": "2",
          "html": "After Seraph lands a hit on a target, it grants an HP shield to all its friendly units equal to 5% of their respective Max HP. The shield cannot be stacked and lasts for 3 seconds. The minimum trigger interval is 1 second."
        },
        {
          "index": "3",
          "html": "After Seraph hits a non-Fortitude target, Punishments will be added. Punishments will be reduced by 1 stack every 5 seconds. If Punishment stacks reach 10, that Wanderer will lose their hyperbody and invincibility and will be unable to regain hyperbody or invincibility for 90 seconds."
        },
        {
          "index": "4",
          "html": "When Seraph receives lethal damage, it becomes invincible for 10 seconds. During that period, it continuously deals a huge amount of damage every second to the surrounding area."
        }
      ]
    },
    {
      "slug": "sobek",
      "name": "Sobek",
      "boss_id": "boss_015",
      "source_psd": "СОБЕК.psd",
      "art": "./assets/bosses/sobek.png",
      "art_object_position": "center center",
      "name_color": "#b190e4",
      "mechanics": [
        {
          "index": "1",
          "html": "<span class=\"fce-card__text-accent\">-100% Crit Rate while having aggro</span>"
        },
        {
          "index": "2",
          "html": "Sobek can be executed. Use weapons with high shatter to break its shield and execute it."
        },
        {
          "index": "3",
          "html": "When Sobek hits a non-Fortitude target, it applies Vulnerability to the target for 10 seconds, stacking up to 10 times."
        },
        {
          "index": "4",
          "html": "Sobek enters a frenzy state, greatly increasing all speeds. <span class=\"fce-card__text-accent\">Becomes immune to control effects.</span>"
        }
      ]
    },
    {
      "slug": "singer",
      "name": "Singer",
      "boss_id": "boss_012",
      "source_psd": "ПЕВЕЦ.psd",
      "art": "./assets/bosses/singer.png",
      "art_object_position": "center center",
      "name_color": "#52d9d5",
      "mechanics": [
        {
          "index": "1",
          "html": "The Singer&#x27;s attacks inflict Corrosion DMG."
        },
        {
          "index": "2",
          "html": "The Singer constantly deals massive Radiation DMG to nearby enemies."
        },
        {
          "index": "3",
          "html": "The Singer summons a decoy every 30 seconds, becoming invincible while the decoy exists. Attack the decoy a set number of times to destroy it and dispel the Singer&#x27;s Invincibility."
        },
        {
          "index": "4",
          "html": "Whenever dealing damage, the Singer inflicts a stack of Corruption, which, upon reaching 20 stacks, reduces the target&#x27;s ATK and movement speed for 15 seconds. <span class=\"fce-card__text-accent\">Debuff reduces base ATK by 30% (Coco matrix).</span>"
        }
      ]
    },
    {
      "slug": "jormungand",
      "name": "Jormungand",
      "boss_id": "boss_047",
      "source_psd": "йомунгард.psd",
      "art": "./assets/bosses/jormungand.png",
      "art_object_position": "center center",
      "name_color": "#4e55df",
      "mechanics": [
        {
          "index": "1",
          "html": "Jormungand gains speed in all actions."
        },
        {
          "index": "2",
          "html": "Jormungand instantly executes targets with less than 20% health."
        },
        {
          "index": "3",
          "html": "Every 10 seconds, Jormungand fires a piercing light beam, dealing damage to all targets on the field."
        },
        {
          "index": "4",
          "html": "There&#x27;s a chance that Jormungand and nearby monsters won&#x27;t take damage when attacked."
        }
      ]
    },
    {
      "slug": "hyena-mech",
      "name": "Hyena Mech",
      "boss_id": "boss_007",
      "source_psd": "Hyena Mech.psd",
      "art": "./assets/bosses/hyena-mech.png",
      "art_object_position": "center center",
      "name_color": "#e4534d",
      "mechanics": [
        {
          "index": "1",
          "html": "Hyena Mech gains a 20% damage increase and one stack of Overheat with each attack. Upon reaching 5 Overheat stacks, it resets and restores a portion of its Max HP. <span class=\"fce-card__text-accent\">Recovers 5% of Max HP after hitting anyone at 5 stacks (the last hit can be dodged so no heal will be provided).</span>"
        },
        {
          "index": "2",
          "html": "Hyena Mech&#x27;s attacks ignore the target&#x27;s resistance."
        },
        {
          "index": "3",
          "html": "Hyena Mech disables the HP shields of surrounding targets every 20s, lasting 10s. <span class=\"fce-card__text-accent\">Removes HP shield and hyperbody once (not continuously for 10s).</span>"
        },
        {
          "index": "4",
          "html": "Hyena Mech frequently unleashes machine gun sweeps, with its range greatly increased."
        }
      ]
    },
    {
      "slug": "nan-yin",
      "name": "Nan Yin",
      "boss_id": "boss_hum_062",
      "source_psd": "screenshot-crop",
      "art": "./assets/bosses/nan-yin.png",
      "art_object_position": "center center",
      "name_color": "#5f8dff",
      "mechanics": [
        {
          "index": "0",
          "html": "<span class=\"fce-card__text-accent\">Has base DMG Reduction 50%. After performing 5 parries, disables it for 1 min.</span>"
        },
        {
          "index": "1",
          "html": "Nan Yin&#x27;s ATK increases over time. Successful counterattacks from enemies remove the ATK increased."
        },
        {
          "index": "2",
          "html": "Nan Yin stuns the selected target for 2 seconds every 5 seconds, ineffective against targets with Fortitude. <span class=\"fce-card__text-accent\">selected = aggro</span>"
        },
        {
          "index": "3",
          "html": "Nan Yin gains additional Damage Reduction, but loses a large amount of HP if shattered. <span class=\"fce-card__text-accent\">Additional 40% DMG Reduction. When 5 parries are performed, she loses 20% of Max HP.</span>"
        },
        {
          "index": "4",
          "html": "Nan Yin negates the target&#x27;s hyperbody for 10 seconds upon hit. <span class=\"fce-card__text-accent\">Removes hyperbody once upon hit, not continuously for 10s.</span>"
        }
      ]
    },
    {
      "slug": "asurada",
      "name": "Asurada",
      "boss_id": "boss_hum_073",
      "source_psd": "trashurada.psd",
      "art": "./assets/bosses/asurada.png",
      "art_object_position": "center center",
      "name_color": "#bb313d",
      "mechanics": [
        {
          "index": "1",
          "html": "Asurada periodically gains damage reduction, which is removed when successfully countered. <span class=\"fce-card__text-accent\">Every 5 seconds gains 1 stack of 10% DMG reduction, up to 8 stacks.</span>"
        },
        {
          "index": "2",
          "html": "When Asurada hits targets, it reduces their Max HP for 10s, stacking up to 3 times. <span class=\"fce-card__text-accent\">Reduces Max HP by 10% per stack.</span>"
        },
        {
          "index": "3",
          "html": "Asurada prevents targets hit from healing for a short period."
        },
        {
          "index": "4",
          "html": "Asurada&#x27;s hits on non-Fortitude targets sear them, dealing damage based on a percentage of their Max HP every second for 10s, stacking up to 3 times. <span class=\"fce-card__text-accent\">DoT: 3%/s per stack based on player Max HP.</span>"
        }
      ]
    },
    {
      "slug": "hive-mother",
      "name": "Hive Mother",
      "boss_id": "boss_hum_069",
      "source_psd": "hive_mother.psd",
      "art": "./assets/bosses/hive-mother.png",
      "art_object_position": "center center",
      "name_color": "#cb60f1",
      "mechanics": [
        {
          "index": "1",
          "html": "The Hive Mother has high Crit Resistance. If her defenses are shattered, her Crit Resistance will temporarily disappear. <span class=\"fce-card__text-accent\">Additional 50% Crit Resistance. Removed for 1 min after shatter.</span>"
        },
        {
          "index": "2",
          "html": "Upon entering battle, the Hive Mother will summon 2 Rampage Prisoners to assist in combat. The Prisoners are in an invincible state, and will die once the Hive Mother is defeated."
        },
        {
          "index": "3",
          "html": "Every 5 seconds, the Hive Mother inflicts lethal damage every second to the locked-on target for 5 seconds. If the target has Fortitude, this damage is significantly reduced."
        },
        {
          "index": "4",
          "html": "Every 15 seconds, the Hive Mother scans her surroundings. If Attack, Balance, Fortitude, and Benediction are not present at the same time, all of the Hive Mother&#x27;s attacks will inflict lethal damage."
        }
      ]
    },
    {
      "slug": "gu-chen",
      "name": "Gu Chen",
      "boss_id": "boss_hum_060",
      "source_psd": "guchen.psd",
      "art": "./assets/bosses/gu-chen.png",
      "art_object_position": "center center",
      "name_color": "#9f95c8",
      "mechanics": [
        {
          "index": "0",
          "html": "<span class=\"fce-card__text-accent\">After successful counter phantasia Gu Chen lose 9% of MAX HP.</span>"
        },
        {
          "index": "1",
          "html": "All attacks of Gu Chen cause additional damage as a percentage of life, with a cooldown of 3 seconds."
        },
        {
          "index": "2",
          "html": "Gu Chen will enter a short period of invincibility every once in a while. <span class=\"fce-card__text-accent\">Every 10 seconds gain invulnerability for 1 second.</span>"
        },
        {
          "index": "3",
          "html": "The speed of all actions of Gu Chen is improved to a certain extent."
        },
        {
          "index": "4",
          "html": "Gu Chen&#x27;s shield will be almost impossible to break."
        }
      ]
    },
    {
      "slug": "xing-tian",
      "name": "Xing Tian",
      "boss_id": "boss_hum_64",
      "source_psd": "Xing Tian.psd",
      "art": "./assets/bosses/xing-tian.png",
      "art_object_position": "center center",
      "name_color": "#ef73ba",
      "mechanics": [
        {
          "index": "1",
          "html": "When Xing Tian&#x27;s health drops below 25%, he will cause damage to the surrounding area and become invincible for 15 seconds. This effect will only be triggered once."
        },
        {
          "index": "2",
          "html": "The damage Xing Tian causes to targets with a higher health percentage than his own is greatly increased."
        },
        {
          "index": "3",
          "html": "When Xing Tian hits a non-selected target, there is a chance that all of the target&#x27;s actions will be greatly reduced for 4 seconds."
        },
        {
          "index": "4",
          "html": "The speed of all Xing Tian&#x27;s actions is greatly increased."
        }
      ]
    },
    {
      "slug": "ying-zhao",
      "name": "Ying Zhao",
      "boss_id": "boss_hum_061",
      "source_psd": "yingzhao.psd",
      "art": "./assets/bosses/ying-zhao.png",
      "art_object_position": "center center",
      "name_color": "#a78fe7",
      "mechanics": [
        {
          "index": "2",
          "html": "Ying Zhao gains a shield every 20 seconds, capable of blocking up to 40 instances of damage."
        },
        {
          "index": "3",
          "html": "Ying Zhao cannot be critically hit."
        },
        {
          "index": "4",
          "html": "Ying Zhao randomly selects 3 targets to form a triangular link, becoming invincible. Only enemies enclosed within the triangle take damage."
        },
        {
          "index": "5",
          "html": "Ying Zhao unleashes damage taken over the past 3 seconds to nearby enemies every 15 seconds. This damage cannot be fatal."
        }
      ]
    },
    {
      "slug": "sphere",
      "name": "Sphere",
      "boss_id": "boss_hum_075",
      "source_psd": "sphere.psd",
      "art": "./assets/bosses/sphere.png",
      "art_object_position": "center center",
      "name_color": "#73d9ee",
      "mechanics": [
        {
          "index": "1",
          "html": "All action speeds of the Sphere are increased."
        },
        {
          "index": "2",
          "html": "Sphere will release an electric current to the surrounding area every 5 seconds. The current will bounce back and forth between nearby targets to cause damage."
        },
        {
          "index": "3",
          "html": "The jump landing point and sliding area of the Sphere will leave an electric current area, causing lightning damage to the targets in the area every second."
        },
        {
          "index": "4",
          "html": "Sphere will add paralysis value to the target when it hits the target. When it is stacked to 20 layers, it will force paralysis for 5 seconds."
        }
      ]
    },
    {
      "slug": "franken",
      "name": "Franken",
      "boss_id": "boss_hum_001",
      "source_psd": "screenshot-crop",
      "art": "./assets/bosses/franken.png",
      "art_object_position": "center center",
      "name_color": "#9a7ce4",
      "mechanics": [
        {
          "index": "1",
          "html": "The interval between shield activations for the Franken is greatly shortened, but maximum health will be lost if the shield is broken. Shield cooldown 20s. Loses 15% of Max HP after shatter every 2nd shield. <span class=\"fce-card__text-accent\">(1-3-5-7)</span>"
        },
        {
          "index": "2",
          "html": "All attacks of the Franken will trigger earthquakes, causing damage and slowing down the target."
        },
        {
          "index": "3",
          "html": "The efficiency of the Franken&#x27;s selected target&#x27;s shield breaking is increased by 100%. Non-selected targets cannot cause damage to the Alien Franken&#x27;s shield."
        },
        {
          "index": "4",
          "html": "The shield value of the Franken is greatly increased, and the damage taken during the shield period is greatly reduced. Franken Shield +100%. <span class=\"fce-card__text-accent\">Additional DMG Reduction 84.5% while shielded.</span>"
        }
      ]
    },
    {
      "slug": "barbarossa",
      "name": "Barbarossa",
      "boss_id": "boss_hum_025",
      "source_psd": "screenshot-crop",
      "art": "./assets/bosses/barbarossa.png",
      "art_object_position": "center center",
      "name_color": "#b972d8",
      "mechanics": [
        {
          "index": "2",
          "html": "Barbarossa gains Bleed upon hitting targets, dealing damage equal to % of Max HP per second for 15s, up to 1 stack."
        },
        {
          "index": "3",
          "html": "Barbarossa enters Rampage Mode, greatly increasing its movement speed."
        },
        {
          "index": "4",
          "html": "Barbarossa increases the biting frequency, ignoring Hyperbody and Invincibility."
        },
        {
          "index": "5",
          "html": "Barbarossa inflicts Fear upon locking a target, greatly reducing their movement speed. The effect is halved against targets with Fortitude."
        }
      ]
    },
    {
      "slug": "zhuyan",
      "name": "Zhuyan",
      "boss_id": "boss_hum_057",
      "source_psd": "bigboss_SY_10.png",
      "art": "./assets/bosses/zhuyan.png",
      "art_object_position": "center center",
      "name_color": "#ff5a4d",
      "mechanics": [
        {
          "index": "1",
          "html": "Zhuyan's attacks carry an additional Powerful Graying Bite effect. Increase corresponding elemental resistance or avoid being hit."
        },
        {
          "index": "2",
          "html": "Zhuyan inflicts Brutality with each hit. At 5 stacks, it triggers an explosion that deals massive damage to the target and nearby enemies."
        },
        {
          "index": "3",
          "html": "Zhuyan can be executed. Use weapons with high Shatter to break its shield and execute it."
        },
        {
          "index": "4",
          "html": "Zhuyan erupts the ground every 5s, dealing lethal damage and leaving pools of lava at the explosion sites."
        }
      ]
    },
    {
      "slug": "fei-lian",
      "name": "Fei Lian",
      "boss_id": "boss_hum_067",
      "source_psd": "BOSS_FL.png",
      "art": "./assets/bosses/fei-lian.png",
      "art_object_position": "center center",
      "name_color": "#d2db4f",
      "mechanics": [
        {
          "index": "1",
          "html": "Grants Fei Lian 1 stack of Damage Reduction of an Element for 3s after getting hit with that Element. Grants up to 1 stack every second."
        },
        {
          "index": "2",
          "html": "Ignores the target's resistances when attacking."
        },
        {
          "index": "3",
          "html": "Owns 5 stacks of Element Shield, each stack reducing the damage Fei Lian takes. Elemental attacks remove the corresponding Shield for 10s."
        },
        {
          "index": "4",
          "html": "Generates Elemental Ores every 15s around Fei Lian. The ores break upon 5 hits of the corresponding Elements but explode if they are not broken within 15s, dealing lethal damage to characters and healing Fei Lian."
        }
      ]
    },
    {
      "slug": "nanto",
      "name": "Nanto",
      "boss_id": "boss_hum_086",
      "source_psd": "BOSS_ND.png",
      "art": "./assets/bosses/nanto.png",
      "art_object_position": "center center",
      "name_color": "#49a6ee",
      "mechanics": [
        {
          "index": "1",
          "html": "Has a chance to stun enemies for 1.5s upon hit."
        },
        {
          "index": "2",
          "html": "Has a chance of gaining a Shield that blocks 1 instance of damage."
        },
        {
          "index": "3",
          "html": "Grants an Attack Boost or Damage Reduction every 10s, lasting for 10s."
        },
        {
          "index": "4",
          "html": "Generates a large-scale explosion every 5s, dealing damage and reducing the target's Attack, Crit, or Resistance randomly for 5s."
        }
      ]
    },
    {
      "slug": "chiron",
      "name": "Chiron",
      "boss_id": "boss_hum_009",
      "source_psd": "bigboss004.png",
      "art": "./assets/bosses/chiron.png",
      "art_object_position": "center center",
      "name_color": "#2fa8c5",
      "mechanics": [
        {
          "index": "1",
          "html": "Increases Chiron the Centaur's Speed."
        },
        {
          "index": "2",
          "html": "Chiron the Centaur sprints more often."
        },
        {
          "index": "3",
          "html": "Chiron the Centaur's attacks ignore Hyperbody."
        },
        {
          "index": "4",
          "html": "Chiron the Centaur creates electromagnetic traps around itself, stunning those who step on them for 3s."
        }
      ]
    },
    {
      "slug": "eva",
      "name": "Eva",
      "boss_id": "boss_hum_045",
      "source_psd": "bigboss069.png",
      "art": "./assets/bosses/eva.png",
      "art_object_position": "center center",
      "name_color": "#cf86c1",
      "mechanics": [
        {
          "index": "1",
          "html": "Abyssant: Eva's attacks inflict Graying Bite."
        },
        {
          "index": "2",
          "html": "Abyssant: Eva deals massive damage, distributed among nearby enemies."
        },
        {
          "index": "3",
          "html": "When below 25% HP, Abyssant: Eva loses 5% of her Max HP per second and deals lethal damage over time to nearby enemies."
        },
        {
          "index": "4",
          "html": "Abyssant: Eva gains Invincibility. A light circle appears nearby every 15s. Abyssant: Eva loses Invincibility for 30s once she steps into the circle."
        }
      ]
    },
    {
      "slug": "phantasmic-scorpion",
      "name": "Scorpion",
      "boss_id": "boss_hum_074",
      "source_psd": "Norn_BOSS_2.png",
      "art": "./assets/bosses/phantasmic-scorpion.png",
      "art_object_position": "center center",
      "name_color": "#b7e84a",
      "name_width": 980,
      "mechanics": [
        {
          "index": "1",
          "html": "Prevents healing on targets hit by Scorpion for 10s."
        },
        {
          "index": "2",
          "html": "Scorpion releases a lethal poison in a large area every 30s."
        },
        {
          "index": "3",
          "html": "Scorpion releases poisonous fog in a random area nearby every 10s, inflicting Slow on those who enter."
        },
        {
          "index": "4",
          "html": "Stone Pillars spawn around the Scorpion every 20s. 10s later, the Scorpion releases poison to all targets not sheltered by the pillars, inflicting an 8-second Stun on them."
        }
      ]
    }
  ],
  "ru": [
    {
      "slug": "chaos-armor",
      "name": "Хаос Армор",
      "boss_id": "boss_hum_046",
      "mechanics": [
        {
          "index": "1",
          "html": "Атаки накладывают мощный эффект Graying Bite. Повышайте соответствующее стихийное сопротивление или уклоняйтесь от попаданий."
        },
        {
          "index": "2",
          "html": "Чем меньше HP босса, тем выше его снижение урона. <span class=\"fce-card__text-accent\">Снижение урона на 20% за каждые потерянные 20% HP.</span> После этого босса можно добить. Используйте оружие с высоким shatter, чтобы сломать щит и выполнить добивание. Урон добивания игнорирует снижение урона босса и зависит от ATK, сопротивлений и бонуса урона Странника."
        },
        {
          "index": "3",
          "html": "Босс получает навык Infernal Flames. Большинство атак босса оставляют на земле большую горящую область, которая непрерывно наносит урон. Не заходите в пылающие зоны."
        },
        {
          "index": "4",
          "html": "По области будут происходить большие случайные взрывы, наносящие смертельный урон при попадании и оставляющие Infernal Flames."
        }
      ]
    },
    {
      "slug": "frigg",
      "name": "Фригг",
      "boss_id": "boss_hum_019",
      "mechanics": [
        {
          "index": "1",
          "html": "Прочность щита Фригг значительно увеличена."
        },
        {
          "index": "2",
          "html": "Фригг получает бафф урона каждый раз, когда попадает по цели. Эффект может накапливаться."
        },
        {
          "index": "3",
          "html": "Фригг входит в режим Rampage, значительно повышая скорость."
        },
        {
          "index": "4",
          "html": "Фригг входит в Extreme Mode: ее скорость повышается, а под ногами остается лед. Если наступить на лед, вы получите урон и замедление, до 3 стаков."
        }
      ]
    },
    {
      "slug": "valkyrie",
      "name": "Валькирия",
      "boss_id": "boss_hum_032",
      "mechanics": [
        {
          "index": "1",
          "html": "Валькирия через равные интервалы оставляет на земле разрушаемые электроды."
        },
        {
          "index": "2",
          "html": "Валькирия становится иммунной к урону 1 раз в секунду."
        },
        {
          "index": "3",
          "html": "Валькирия через равные интервалы оставляет вокруг себя разрушаемые электроды. Эти электроды периодически испускают круговой электрический разряд по области вокруг."
        },
        {
          "index": "4",
          "html": "Валькирия через равные интервалы призывает вокруг себя молнии, наносящие смертельный урон и накладывающие electrified. Если по electrified-цели попадает volt-атака, срабатывает цепная молния."
        }
      ]
    },
    {
      "slug": "culton",
      "name": "Калтон",
      "boss_id": "boss_hum_036",
      "mechanics": [
        {
          "index": "1",
          "html": "Калтон каждую секунду накладывает Hostility на выбранную цель. Каждый стак замедляет цель на 5 секунд, до 5 стаков."
        },
        {
          "index": "2",
          "html": "Каждые 30 секунд Калтон вызывает хаос, разворачивая управление движением Странников на 15 секунд."
        },
        {
          "index": "3",
          "html": "Калтон становится неуязвимым на 3 секунды каждый раз после потери 10% Max HP."
        },
        {
          "index": "4",
          "html": "В финальной фазе Калтон призывает красные столбы. Каждый столб увеличивает его урон и снижение урона на 20%. Столкните Калтона со столбами, чтобы отключить баффы."
        }
      ]
    },
    {
      "slug": "iron-tomb",
      "name": "Саркофаг",
      "boss_id": "boss_hum_037",
      "mechanics": [
        {
          "index": "1",
          "html": "Атаки Саркофага имеют шанс наложить эффект Countermove на 5 секунд, отключая hyperbody цели на все время действия эффекта."
        },
        {
          "index": "2",
          "html": "Каждые 20 секунд Саркофаг получает снижение урона на основе потерянного Max HP на 20 секунд. <span class=\"fce-card__text-accent\">Каждые 20 секунд рассчитывается снижение урона по ОБЩЕЙ потере HP. Первые 20% потерянного HP: каждый 1% HP = 0.25% снижения урона. Далее каждый 1% HP = 0.5% снижения урона.</span>"
        },
        {
          "index": "3",
          "html": "Каждые 8 секунд атаки Саркофага накладывают Maim, значительно снижая наносимый урон и получаемое лечение у целей без Fortitude на 8 секунд. <span class=\"fce-card__text-accent\">-50% наносимого урона</span>"
        },
        {
          "index": "4",
          "html": "Каждые 20 секунд Саркофаг случайно связывает 2 игроков в радиусе, снижая их финальный урон на 30%; каждый связанный игрок увеличивает финальный урон Саркофага на 30%. Уйдя подальше от босса, связь можно разорвать."
        }
      ]
    },
    {
      "slug": "gaia",
      "name": "Гайя",
      "boss_id": "boss_hum_042",
      "mechanics": [
        {
          "index": "1",
          "html": "Гайя каждым попаданием накладывает Bonecrush на цели без Fortitude. На 20 стаках дебафф вызывает Cripple, резко снижая наносимый ими урон на 10 секунд."
        },
        {
          "index": "2",
          "html": "Каждые 15 секунд Гайя случайно выбирает цель. Через 5 секунд выбранная цель начинает наносить всем союзникам, кроме себя, массовый смертельный урон каждую секунду в течение 5 секунд."
        },
        {
          "index": "3",
          "html": "Цели, пораженные Гайей, замедляются на 5 секунд, до 2 стаков."
        },
        {
          "index": "4",
          "html": "После разрушения щита Гайя наносит урон по области каждую секунду в течение 10 секунд. Пораженные цели получают 15% vulnerability на 10 секунд, до 3 стаков."
        }
      ]
    },
    {
      "slug": "sweetie",
      "name": "Милашка",
      "boss_id": "boss_hum_020",
      "mechanics": [
        {
          "index": "1",
          "html": "Каждые 25 секунд Милашка накладывает штраф на 2-4 случайные ближайшие цели. Если они совершают какие-либо действия в течение 5 секунд после наложения штрафа, то получают урон."
        },
        {
          "index": "2",
          "html": "Увеличивает скорость передвижения Милашки и снижает скорость передвижения всех ближайших целей."
        },
        {
          "index": "3",
          "html": "Каждые 15 секунд Милашка случайно выбирает цель на поле и наносит ей огромный урон каждую секунду в течение 15 секунд, отдавая приоритет целям с Fortitude Resonance."
        },
        {
          "index": "4",
          "html": "Милашка связывает всех союзных Странников на поле. Каждая цель получает урон пропорционально проценту урона, полученного другими связанными целями. <span class=\"fce-card__text-accent\"> Каждый игрок делится 10% входящего урона. Этот урон игнорирует сопротивления и снижение урона (кроме Аски).</span>"
        }
      ]
    },
    {
      "slug": "merbelle",
      "name": "Мербелль",
      "boss_id": "boss_065",
      "mechanics": [
        {
          "index": "1",
          "html": "Каждый раз, когда Мербелль теряет определенное количество HP, ее атака увеличивается."
        },
        {
          "index": "2",
          "html": "Когда у Мербелль есть щит, она получает дополнительное снижение урона и значительно более прочный щит. <span class=\"fce-card__text-accent\">Дополнительное снижение урона 60%.</span>"
        },
        {
          "index": "3",
          "html": "Каждый раз, когда Мербелль наносит урон, она накладывает 1 стак Flashfreeze. Когда стаков становится 15, они снимаются, а Странник получает сильное замедление на 6 секунд."
        },
        {
          "index": "4",
          "html": "Каждые 15 секунд Мербелль выпускает в цель ледяной столб, наносящий огромный урон. Столб остается на поле и восстанавливает 3% Max HP Мербелль каждые 10 секунд. Ледяной столб можно уничтожить несколькими атаками."
        }
      ]
    },
    {
      "slug": "frost-bot",
      "name": "Фрост Бот",
      "boss_id": "boss_017",
      "mechanics": [
        {
          "index": "1",
          "html": "Фрост Бот постоянно создает вокруг себя генераторы позиционирования. Каждый генератор дает Фрост Боту снижение урона и может быть разрушен несколькими атаками. <span class=\"fce-card__text-accent\"> Снижение урона 20% за каждый шар, максимум 90%.</span>"
        },
        {
          "index": "2",
          "html": "Фрост Бот ремонтирует себя, медленно восстанавливая HP. <span class=\"fce-card__text-accent\"> Восстанавливает 0.5% Max HP каждые 2 секунды.</span>"
        },
        {
          "index": "3",
          "html": "Скорость передвижения Фрост Бота значительно увеличена."
        },
        {
          "index": "4",
          "html": "Каждую секунду Фрост Бот выпускает вокруг себя мощный холод, постоянно замедляя ближайшие цели."
        }
      ]
    },
    {
      "slug": "apophis",
      "name": "Апофис",
      "boss_id": "boss_014",
      "mechanics": [
        {
          "index": "1",
          "html": "Атаки накладывают мощный эффект Graying Bite. Повышайте соответствующее стихийное сопротивление или уклоняйтесь от попаданий."
        },
        {
          "index": "2",
          "html": "Апофиса можно добить. Используйте оружие с высоким shatter, чтобы сломать его щит и казнить босса."
        },
        {
          "index": "3",
          "html": "Скорость передвижения Апофиса значительно увеличена."
        },
        {
          "index": "4",
          "html": "Отменяет hyperbody у целей вокруг Апофиса."
        }
      ]
    },
    {
      "slug": "minotaur",
      "name": "Минотавр",
      "boss_id": "boss_002",
      "mechanics": [
        {
          "index": "1",
          "html": "Минотавр значительно снижает получаемый урон от основной агро-цели. <span class=\"fce-card__text-accent\">Снижение урона от агро 80%.</span>"
        },
        {
          "index": "2",
          "html": "Минотавра можно добить. Используйте оружие с высоким shatter, чтобы сломать щит и казнить босса."
        },
        {
          "index": "3",
          "html": "Каждые 15 секунд Минотавр случайно выбирает цель с Benediction и накладывает Toxicitea, превращая ее лечение в эквивалентный урон. Длится 10 секунд."
        },
        {
          "index": "4",
          "html": "Каждые 15 секунд Минотавр проверяет всех Странников. Если кто-то находится в радиусе 5 метров без других союзников рядом, этот Странник теряет hyperbody и неуязвимость и не может восстановить их в течение 90 секунд."
        }
      ]
    },
    {
      "slug": "rudolph",
      "name": "Рудольф",
      "boss_id": "boss_030",
      "mechanics": [
        {
          "index": "1",
          "html": "Прочность щита Рудольфа значительно увеличена."
        },
        {
          "index": "2",
          "html": "Рудольф получает огромное снижение урона спереди, но получает повышенный урон сзади. <span class=\"fce-card__text-accent\"> Снижение урона спереди 60%.</span>"
        },
        {
          "index": "3",
          "html": "Рудольф через заданные интервалы активирует широкую Phantasia на 5 секунд."
        },
        {
          "index": "4",
          "html": "Рудольф входит в режим Rampage, значительно повышая скорость передвижения."
        }
      ]
    },
    {
      "slug": "seraph",
      "name": "Сераф",
      "boss_id": "boss_010",
      "mechanics": [
        {
          "index": "1",
          "html": "Атаки Серафа дополнительно накладывают мощный Graying Bite."
        },
        {
          "index": "2",
          "html": "После попадания по цели Сераф дает всем союзным юнитам щит в размере 5% от их Max HP. Щит не стакается, длится 3 секунды. Минимальный интервал срабатывания 1 секунда."
        },
        {
          "index": "3",
          "html": "После попадания по цели без Fortitude Сераф накладывает Punishment. Один стак снимается каждые 5 секунд. Если стаков становится 10, Странник теряет hyperbody и неуязвимость и не может вернуть их в течение 90 секунд."
        },
        {
          "index": "4",
          "html": "При получении смертельного урона Сераф становится неуязвимым на 10 секунд. В этот период он каждую секунду наносит огромный урон по области вокруг себя."
        }
      ]
    },
    {
      "slug": "sobek",
      "name": "Собек",
      "boss_id": "boss_015",
      "mechanics": [
        {
          "index": "1",
          "html": "Когда Собек фиксируется на цели, ее шанс критического удара сильно снижается. <span class=\"fce-card__text-accent\">-100% crit rate, пока на вас агро</span>"
        },
        {
          "index": "2",
          "html": "Собека можно добить. Используйте оружие с высоким shatter, чтобы сломать щит и казнить босса."
        },
        {
          "index": "3",
          "html": "Когда Собек попадает по цели без Fortitude, он накладывает Vulnerability на 10 секунд, до 10 стаков."
        },
        {
          "index": "4",
          "html": "Собек впадает в ярость, значительно повышая все скорости. <span class=\"fce-card__text-accent\"> Получает иммунитет к эффектам контроля.</span>"
        }
      ]
    },
    {
      "slug": "singer",
      "name": "Сингер",
      "boss_id": "boss_012",
      "mechanics": [
        {
          "index": "1",
          "html": "Атаки Сингера наносят Corrosion DMG."
        },
        {
          "index": "2",
          "html": "Сингер постоянно наносит ближайшим врагам огромный Radiation DMG."
        },
        {
          "index": "3",
          "html": "Каждые 30 секунд Сингер призывает приманку и становится неуязвимым, пока она существует. Атакуйте приманку нужное число раз, чтобы уничтожить ее и снять неуязвимость Сингера."
        },
        {
          "index": "4",
          "html": "Каждый нанесенный удар Сингера накладывает стак Corruption. При достижении 20 стаков у цели снижаются ATK и скорость передвижения на 15 секунд. <span class=\"fce-card__text-accent\"> Дебафф снижает базовый ATK на 30% (матрица Коко).</span>"
        }
      ]
    },
    {
      "slug": "jormungand",
      "name": "Йормунганд",
      "boss_id": "boss_047",
      "mechanics": [
        {
          "index": "1",
          "html": "Йормунганд ускоряет все свои действия."
        },
        {
          "index": "2",
          "html": "Йормунганд мгновенно добивает цель, если у нее меньше 20% здоровья."
        },
        {
          "index": "3",
          "html": "Каждые 10 секунд Йормунганд выпускает пронзающий луч света, нанося урон всем целям на поле."
        },
        {
          "index": "4",
          "html": "Есть шанс, что Йормунганд и ближайшие монстры не будут получать урон при атаке."
        }
      ]
    },
    {
      "slug": "hyena-mech",
      "name": "Гиена-Мех",
      "boss_id": "boss_007",
      "mechanics": [
        {
          "index": "1",
          "html": "Гиена-Мех получает +20% к урону и 1 стак Overheat с каждой атакой. При достижении 5 стаков Overheat эффект сбрасывается, а босс восстанавливает часть Max HP. <span class=\"fce-card__text-accent\">Восстанавливает 5% Max HP после попадания по кому-либо с 5 стаками (от последнего удара можно увернуться, тогда лечения не будет)</span>"
        },
        {
          "index": "2",
          "html": "Атаки Гиена-Меха игнорируют сопротивления цели."
        },
        {
          "index": "3",
          "html": "Каждые 20 секунд Гиена-Мех отключает HP-щиты окружающих целей на 10 секунд. <span class=\"fce-card__text-accent\">Одноразово снимает HP-щит и hyperbody, а не на все 10 секунд.</span>"
        },
        {
          "index": "4",
          "html": "Гиена-Мех часто выпускает длинные очереди из пулемета, причем их дальность сильно увеличена."
        }
      ]
    },
    {
      "slug": "nan-yin",
      "name": "Нань Инь",
      "boss_id": "boss_hum_062",
      "mechanics": [
        {
          "index": "0",
          "html": "<span class=\"fce-card__text-accent\">Базовое снижение урона 50%. После 5 успешных парирований отключается на 1 минуту.</span>"
        },
        {
          "index": "1",
          "html": "ATK Нань Инь со временем увеличивается. Успешные контратаки врагов снимают это увеличение."
        },
        {
          "index": "2",
          "html": "Нань Инь оглушает выбранную цель на 2 секунды каждые 5 секунд; не действует на цели с Fortitude. <span class=\"fce-card__text-accent\">selected = aggro</span>"
        },
        {
          "index": "3",
          "html": "Нань Инь получает дополнительное снижение урона, но теряет много HP при shatter. <span class=\"fce-card__text-accent\">Дополнительное снижение урона 40%. После 5 парирований теряет 20% Max HP.</span>"
        },
        {
          "index": "4",
          "html": "При попадании Нань Инь отключает hyperbody цели на 10 секунд. <span class=\"fce-card__text-accent\">Снимает один раз, а не на все 10 секунд.</span>"
        }
      ]
    },
    {
      "slug": "asurada",
      "name": "Асурада",
      "boss_id": "boss_hum_073",
      "mechanics": [
        {
          "index": "1",
          "html": "Асурада периодически получает снижение урона, которое снимается успешным парированием. <span class=\"fce-card__text-accent\">Каждые 5 секунд получает 1 слой снижения урона на 10%, до 8 слоев.</span>"
        },
        {
          "index": "2",
          "html": "Когда Асурада попадает по цели, он снижает ее Max HP на 10 секунд, до 3 стаков. <span class=\"fce-card__text-accent\">Снижение Max HP на 10% за стак.</span>"
        },
        {
          "index": "3",
          "html": "Асурада ненадолго запрещает лечить пораженные цели."
        },
        {
          "index": "4",
          "html": "Попадания Асурады по целям без Fortitude поджигают их, нанося урон в процентах от Max HP каждую секунду в течение 10 секунд, до 3 стаков. <span class=\"fce-card__text-accent\"> DoT 3%/сек за каждый стак от максимального HP игрока.</span>"
        }
      ]
    },
    {
      "slug": "hive-mother",
      "name": "Улей-Мать",
      "boss_id": "boss_hum_069",
      "mechanics": [
        {
          "index": "1",
          "html": "У Улья-Матери высокая сопротивляемость критическим ударам. Если ее защиту разбить, эта крит-сопротивляемость временно исчезнет. <span class=\"fce-card__text-accent\">Дополнительно 50% crit resist. Снимается на 1 минуту после shatter.</span>"
        },
        {
          "index": "2",
          "html": "При входе в бой Улей-Мать призывает 2 Rampage Prisoners для помощи в бою. Они находятся в состоянии неуязвимости и умрут только после смерти самой Улья-Матери."
        },
        {
          "index": "3",
          "html": "Каждые 5 секунд Улей-Мать наносит смертельный урон каждую секунду в течение 5 секунд цели, на которую зафиксирована. Если цель имеет Fortitude, этот урон значительно снижается."
        },
        {
          "index": "4",
          "html": "Каждые 15 секунд Улей-Мать сканирует окружение. Если на поле одновременно нет Attack, Balance, Fortitude и Benediction, все ее атаки начинают наносить смертельный урон."
        }
      ]
    },
    {
      "slug": "gu-chen",
      "name": "Гу Чэнь",
      "boss_id": "boss_hum_060",
      "mechanics": [
        {
          "index": "0",
          "html": "<span class=\"fce-card__text-accent\">После успешной counter phantasia Гу Чэнь теряет 9% MAX HP.</span>"
        },
        {
          "index": "1",
          "html": "Все атаки Гу Чэня наносят дополнительный урон в процентах от HP, с кулдауном 3 секунды."
        },
        {
          "index": "2",
          "html": "Гу Чэнь периодически входит в короткую неуязвимость. <span class=\"fce-card__text-accent\">Каждые 10 секунд получает неуязвимость на 1 секунду.</span>"
        },
        {
          "index": "3",
          "html": "Скорость всех действий Гу Чэня умеренно повышена."
        },
        {
          "index": "4",
          "html": "Щит Гу Чэня почти невозможно сломать."
        }
      ]
    },
    {
      "slug": "xing-tian",
      "name": "Син Тянь",
      "boss_id": "boss_hum_64",
      "mechanics": [
        {
          "index": "1",
          "html": "Когда здоровье Син Тяня падает ниже 25%, он наносит урон вокруг себя и становится неуязвимым на 15 секунд. Этот эффект срабатывает только один раз."
        },
        {
          "index": "2",
          "html": "Урон, который Син Тянь наносит целям с более высоким процентом HP, чем у него самого, значительно увеличен."
        },
        {
          "index": "3",
          "html": "Когда Син Тянь попадает по невыбранной цели, есть шанс сильно замедлить все действия этой цели на 4 секунды."
        },
        {
          "index": "4",
          "html": "Скорость всех действий Син Тяня значительно повышена."
        }
      ]
    },
    {
      "slug": "ying-zhao",
      "name": "Ин Чжао",
      "boss_id": "boss_hum_061",
      "mechanics": [
        {
          "index": "2",
          "html": "Ин Чжао получает щит каждые 20 секунд, способный заблокировать до 40 попаданий."
        },
        {
          "index": "3",
          "html": "По Ин Чжао невозможно нанести критический удар."
        },
        {
          "index": "4",
          "html": "Ин Чжао случайно выбирает 3 цели, связывает их треугольником и становится неуязвимым. Урон получают только враги внутри треугольника."
        },
        {
          "index": "5",
          "html": "Каждые 15 секунд Ин Чжао высвобождает по ближайшим врагам урон, полученный им за последние 3 секунды. Этот урон не может быть смертельным."
        }
      ]
    },
    {
      "slug": "sphere",
      "name": "Сфера",
      "boss_id": "boss_hum_075",
      "mechanics": [
        {
          "index": "1",
          "html": "Скорость всех действий Сферы увеличена."
        },
        {
          "index": "2",
          "html": "Каждые 5 секунд Сфера выпускает электрический ток по области вокруг. Разряд рикошетит между ближайшими целями и наносит урон."
        },
        {
          "index": "3",
          "html": "Точка приземления прыжка и зона скольжения Сферы оставляют электрическое поле, которое каждую секунду наносит молниеносный урон целям внутри."
        },
        {
          "index": "4",
          "html": "При попадании Сфера накапливает у цели значение paralysis. На 20 стаках принудительно накладывается паралич на 5 секунд."
        }
      ]
    },
    {
      "slug": "franken",
      "name": "Франкен",
      "boss_id": "boss_hum_001",
      "mechanics": [
        {
          "index": "1",
          "html": "Интервал между активациями щита Франкена сильно сокращен, но при разрушении щита он теряет Max HP. Перезарядка щита 20 секунд. Потеря 15% Max HP после разрушения каждого 2-го щита. <span class=\"fce-card__text-accent\">(1-3-5-7)</span>"
        },
        {
          "index": "2",
          "html": "Все атаки Франкена вызывают землетрясения, наносящие урон и замедляющие цель."
        },
        {
          "index": "3",
          "html": "Эффективность разрушения щита у выбранной цели Франкена увеличена на 100%. Невыбранные цели не могут наносить урон щиту Alien Franken."
        },
        {
          "index": "4",
          "html": "Прочность щита Франкена значительно увеличена, а получаемый урон во время действия щита сильно снижен. Щит Франкена +100%. <span class=\"fce-card__text-accent\">Дополнительное снижение урона 84.5% пока щит активен.</span>"
        }
      ]
    },
    {
      "slug": "barbarossa",
      "name": "Барбаросса",
      "boss_id": "boss_hum_025",
      "mechanics": [
        {
          "index": "2",
          "html": "Барбаросса накладывает Bleed при попадании по цели, нанося урон, равный % от Max HP в секунду, в течение 15 секунд, до 1 стака."
        },
        {
          "index": "3",
          "html": "Барбаросса входит в режим Rampage, значительно увеличивая скорость передвижения."
        },
        {
          "index": "4",
          "html": "Барбаросса увеличивает частоту укусов, игнорируя Hyperbody и Invincibility."
        },
        {
          "index": "5",
          "html": "Барбаросса накладывает Fear при захвате цели, сильно снижая ее скорость передвижения. Против целей с Fortitude эффект ослаблен вдвое."
        }
      ]
    },
    {
      "slug": "zhuyan",
      "name": "Чжуянь",
      "boss_id": "boss_hum_057",
      "mechanics": [
        {
          "index": "1",
          "html": "Атаки Чжуяня дополнительно накладывают мощный эффект Graying Bite. Повышайте соответствующее стихийное сопротивление или уклоняйтесь от попаданий."
        },
        {
          "index": "2",
          "html": "Чжуянь каждым попаданием накладывает Brutality. На 5 стаках происходит взрыв, наносящий огромный урон цели и ближайшим врагам."
        },
        {
          "index": "3",
          "html": "Чжуяня можно добить. Используйте оружие с высоким Shatter, чтобы сломать его щит и выполнить добивание."
        },
        {
          "index": "4",
          "html": "Каждые 5 секунд Чжуянь взрывает землю, нанося смертельный урон и оставляя лужи лавы в местах взрывов."
        }
      ]
    },
    {
      "slug": "fei-lian",
      "name": "Фэй Лянь",
      "boss_id": "boss_hum_067",
      "mechanics": [
        {
          "index": "1",
          "html": "После получения урона стихией Фэй Лянь получает 1 стак снижения урона от этой стихии на 3 секунды. Может получать не более 1 стака в секунду."
        },
        {
          "index": "2",
          "html": "Игнорирует сопротивления цели при атаке."
        },
        {
          "index": "3",
          "html": "Имеет 5 стаков Element Shield; каждый стак снижает получаемый Фэй Лянем урон. Стихийные атаки снимают соответствующий Shield на 10 секунд."
        },
        {
          "index": "4",
          "html": "Каждые 15 секунд вокруг Фэй Ляня появляются Elemental Ores. Они разрушаются после 5 попаданий соответствующими стихиями, но если не уничтожить их за 15 секунд, они взрываются, наносят персонажам смертельный урон и исцеляют Фэй Ляня."
        }
      ]
    },
    {
      "slug": "nanto",
      "name": "Нанто",
      "boss_id": "boss_hum_086",
      "mechanics": [
        {
          "index": "1",
          "html": "При попадании имеет шанс оглушить врагов на 1.5 секунды."
        },
        {
          "index": "2",
          "html": "Имеет шанс получить Shield, который блокирует 1 атаку (инстанс урона)."
        },
        {
          "index": "3",
          "html": "Каждые 10 секунд получает Attack Boost или Damage Reduction на 10 секунд."
        },
        {
          "index": "4",
          "html": "Каждые 5 секунд создает большой взрыв, который наносит урон и случайным образом снижает Attack, Crit или Resistance цели на 5 секунд."
        }
      ]
    },
    {
      "slug": "chiron",
      "name": "Хирон",
      "boss_id": "boss_hum_009",
      "mechanics": [
        {
          "index": "1",
          "html": "Увеличивает скорость Хирона-кентавра."
        },
        {
          "index": "2",
          "html": "Хирон-кентавр чаще выполняет рывок."
        },
        {
          "index": "3",
          "html": "Атаки Хирона-кентавра игнорируют Hyperbody."
        },
        {
          "index": "4",
          "html": "Хирон-кентавр создает вокруг себя электромагнитные ловушки, оглушающие наступивших на них на 3 секунды."
        }
      ]
    },
    {
      "slug": "eva",
      "name": "Ева",
      "boss_id": "boss_hum_045",
      "mechanics": [
        {
          "index": "1",
          "html": "Abyssant: Eva накладывает Graying Bite своими атаками."
        },
        {
          "index": "2",
          "html": "Abyssant: Eva наносит огромный урон, распределенный между ближайшими врагами."
        },
        {
          "index": "3",
          "html": "Когда HP опускается ниже 25%, Abyssant: Eva теряет 5% Max HP в секунду и наносит ближайшим врагам смертельный периодический урон."
        },
        {
          "index": "4",
          "html": "Abyssant: Eva получает Invincibility. Каждые 15 секунд рядом появляется световой круг. Как только Abyssant: Eva заходит в этот круг, она теряет Invincibility на 30 секунд."
        }
      ]
    },
    {
      "slug": "phantasmic-scorpion",
      "name": "Скорпион",
      "boss_id": "boss_hum_074",
      "mechanics": [
        {
          "index": "1",
          "html": "Запрещает лечение целям, пораженным Скорпионом, на 10 секунд."
        },
        {
          "index": "2",
          "html": "Каждые 30 секунд Скорпион выпускает смертельный яд по большой области."
        },
        {
          "index": "3",
          "html": "Каждые 10 секунд Скорпион выпускает ядовитый туман в случайной ближайшей области, накладывая Slow на вошедших в него."
        },
        {
          "index": "4",
          "html": "Каждые 20 секунд вокруг Скорпиона появляются каменные столбы (Stone Pillars). Еще через 10 секунд Скорпион выпускает яд по всем целям, которые не укрылись за столбами, накладывая на них Stun на 8 секунд."
        }
      ]
    }
  ]
};
