(function () {
  const translations = {
    en: {
      eyebrow: "MULTYPE",
      title: "Multiplicative buffs",
      description: "Buff grouping and multiplier data. Columns multiply with each other; values in the same column are additive.",
      loadingTitle: "Loading datamine JSON...",
      loadingBody: "Building the Main / Sub / Value model and rename dictionary.",
      loadError: "Load error",
      source: "Source",
      sourceFile: "Source file",
      total: "Total",
      categories: "categories",
      subcategories: "subcategories",
      buffs: "buffs",
      openJson: "Open local JSON",
      viewSource: "View exporter source",
      renamed: "Renamed",
      combined: "Combined",
      datamined: "Datamined",
      search: "Search",
      searchPlaceholder: "Search original keys or renamed labels...",
      main: "Main",
      sub: "Sub",
      allMain: "All Main",
      allSub: "All Sub",
      all: "All",
      renamedOnly: "Renamed only",
      unrenamedOnly: "Unrenamed only",
      emptyTitle: "Nothing matched",
      emptyBody: "Try another mode, clear filters, or remove the search query.",
      subColumns: "sub columns",
      files: "files",
      zoomOut: "Zoom out",
      zoomIn: "Zoom in",
      zoomFit: "Fit",
      zoomFitTitle: "Fit table to width",
      zoomResetTitle: "Click to reset to 80%",
      resetFilters: "Reset filters",
      filtersActive: "filters active",
      focusTable: "Focus table",
      displayMode: "Display",
      renameStatus: "Rename status",
      tableScale: "Table scale",
      exportImage: "Export image",
      exportTableImage: "Export table image",
      currentFilteredTable: "Current filtered table",
      closeExport: "Close export",
      exportQuality: "Quality",
      palette: "Palette",
      paletteLight: "Light",
      paletteDark: "Dark",
      output: "Output",
      canvas: "Canvas",
      estimatedPng: "Est. PNG",
      raw: "raw",
      exportPng: "Export PNG",
      exportPreparing: "Preparing table…",
      exportRendering: "Rendering image…",
      exportEncoding: "Encoding PNG…",
      exportReady: "Ready to export.",
      exportComplete: "PNG downloaded.",
      exportNothing: "Nothing to export for the current filters.",
      exportTooLarge: "This table is too large to export as a single PNG in this browser.",
      exportNarrow: "Choose a lower quality or narrow the table using the available filters.",
      exportMeasureError: "Could not measure the table for export.",
      exportRendererError: "Could not render the table image.",
      exportBlobError: "Could not encode the PNG."
    },
    ru: {
      eyebrow: "MULTYPE",
      title: "Мультипликативные усиления",
      description: "Группировка усилений и коэффициенты. Разные столбцы перемножаются, а значения внутри одного столбца складываются.",
      loadingTitle: "Загрузка данных...",
      loadingBody: "Формируем структуру Main / Sub / Value и словарь переименований.",
      loadError: "Ошибка загрузки",
      source: "Источник",
      sourceFile: "Файл данных",
      total: "Всего",
      categories: "категорий",
      subcategories: "подкатегорий",
      buffs: "усилений",
      openJson: "Открыть локальный JSON",
      viewSource: "Открыть источник экспортёра",
      renamed: "Переименованные",
      combined: "Вместе",
      datamined: "Исходные",
      search: "Поиск",
      searchPlaceholder: "Поиск по исходным ключам и новым названиям...",
      main: "Main",
      sub: "Sub",
      allMain: "Все Main",
      allSub: "Все Sub",
      all: "Все",
      renamedOnly: "Только переименованные",
      unrenamedOnly: "Без переименования",
      emptyTitle: "Ничего не найдено",
      emptyBody: "Смените режим, сбросьте фильтры или очистите поисковый запрос.",
      subColumns: "подкатегорий",
      files: "файлов",
      zoomOut: "Уменьшить масштаб",
      zoomIn: "Увеличить масштаб",
      zoomFit: "По ширине",
      zoomFitTitle: "Подогнать таблицу по ширине экрана",
      zoomResetTitle: "Нажмите для сброса на 80%",
      resetFilters: "Сбросить фильтры",
      filtersActive: "активных фильтра",
      focusTable: "Перейти к таблице",
      displayMode: "Отображение",
      renameStatus: "Статус названий",
      tableScale: "Масштаб таблицы",
      exportImage: "Экспорт изображения",
      exportTableImage: "Экспорт таблицы",
      currentFilteredTable: "Текущая отфильтрованная таблица",
      closeExport: "Закрыть экспорт",
      exportQuality: "Качество",
      palette: "Палитра",
      paletteLight: "Светлая",
      paletteDark: "Тёмная",
      output: "Размер",
      canvas: "Холст",
      estimatedPng: "Оценочный размер PNG",
      raw: "без сжатия",
      exportPng: "Экспорт PNG",
      exportPreparing: "Подготавливаем таблицу…",
      exportRendering: "Создаём изображение…",
      exportEncoding: "Кодируем PNG…",
      exportReady: "Готово к экспорту.",
      exportComplete: "PNG скачан.",
      exportNothing: "При текущих фильтрах экспортировать нечего.",
      exportTooLarge: "Эта таблица слишком велика для экспорта одним PNG в этом браузере.",
      exportNarrow: "Выберите качество ниже или сузьте таблицу с помощью фильтров.",
      exportMeasureError: "Не удалось рассчитать размер таблицы для экспорта.",
      exportRendererError: "Не удалось создать изображение таблицы.",
      exportBlobError: "Не удалось закодировать PNG."
    }
  };

  window.addEventListener("DOMContentLoaded", () => {
    if (!window.TofMultypeCore) {
      return;
    }

    const initialLanguage = window.DatamineHeader?.getLanguage() === "ru" ? "ru" : "en";
    const app = window.TofMultypeCore.createMultypeApp({
      rootSelector: "[data-multype-app]",
      pageKind: "public",
      initialMode: "renamed",
      dataUrl: "./data/module_extra_to_files_mapping3.json",
      renamesUrl: "./data/renames.base.json",
      storageKey: "tof-multype-local-renames-v1",
      language: initialLanguage,
      translations,
      pageTitle: "Multype datamine viewer",
      pageEyebrow: "Datamine / Multype",
      pageDescription:
        "Datamined buff categories from the Tower of Fantasy exporter scanner repo. Different columns are multiplicative, the same column is additive. If several fields are merged into one, they are replaceable; if not, they are stackable, but not always XD."
    });

    window.addEventListener("datamine:language-change", (event) => {
      const language = event.detail?.language === "ru" ? "ru" : "en";
      app.setLanguage(language);
    });
  });
})();
